//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5485 版自动生成。
// 
#pragma warning disable 1591

namespace SFYWebApi.net.sogal.www {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://eshopinf.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPoRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHQPoRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetJJTPoRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPoRequisitionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPoKineticOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePoKineticOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::SFYWebApi.Properties.Settings.Default.SFYWebApi_net_sogal_www_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetPoRequisitionCompletedEventHandler GetPoRequisitionCompleted;
        
        /// <remarks/>
        public event GetHQPoRequisitionCompletedEventHandler GetHQPoRequisitionCompleted;
        
        /// <remarks/>
        public event GetJJTPoRequisitionCompletedEventHandler GetJJTPoRequisitionCompleted;
        
        /// <remarks/>
        public event AddPoRequisitionCompletedEventHandler AddPoRequisitionCompleted;
        
        /// <remarks/>
        public event GetPoKineticCompletedEventHandler GetPoKineticCompleted;
        
        /// <remarks/>
        public event UpdatePoKineticCompletedEventHandler UpdatePoKineticCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eshopinf.org/HelloWorld", RequestNamespace="http://eshopinf.org/", ResponseNamespace="http://eshopinf.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eshopinf.org/GetPoRequisition", RequestNamespace="http://eshopinf.org/", ResponseNamespace="http://eshopinf.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPoRequisition(System.DateTime creationDayFrom, System.DateTime creationDayTo) {
            object[] results = this.Invoke("GetPoRequisition", new object[] {
                        creationDayFrom,
                        creationDayTo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPoRequisitionAsync(System.DateTime creationDayFrom, System.DateTime creationDayTo) {
            this.GetPoRequisitionAsync(creationDayFrom, creationDayTo, null);
        }
        
        /// <remarks/>
        public void GetPoRequisitionAsync(System.DateTime creationDayFrom, System.DateTime creationDayTo, object userState) {
            if ((this.GetPoRequisitionOperationCompleted == null)) {
                this.GetPoRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPoRequisitionOperationCompleted);
            }
            this.InvokeAsync("GetPoRequisition", new object[] {
                        creationDayFrom,
                        creationDayTo}, this.GetPoRequisitionOperationCompleted, userState);
        }
        
        private void OnGetPoRequisitionOperationCompleted(object arg) {
            if ((this.GetPoRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPoRequisitionCompleted(this, new GetPoRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eshopinf.org/GetHQPoRequisition", RequestNamespace="http://eshopinf.org/", ResponseNamespace="http://eshopinf.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHQPoRequisition(System.DateTime dayFrom, System.DateTime dayTo) {
            object[] results = this.Invoke("GetHQPoRequisition", new object[] {
                        dayFrom,
                        dayTo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetHQPoRequisitionAsync(System.DateTime dayFrom, System.DateTime dayTo) {
            this.GetHQPoRequisitionAsync(dayFrom, dayTo, null);
        }
        
        /// <remarks/>
        public void GetHQPoRequisitionAsync(System.DateTime dayFrom, System.DateTime dayTo, object userState) {
            if ((this.GetHQPoRequisitionOperationCompleted == null)) {
                this.GetHQPoRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHQPoRequisitionOperationCompleted);
            }
            this.InvokeAsync("GetHQPoRequisition", new object[] {
                        dayFrom,
                        dayTo}, this.GetHQPoRequisitionOperationCompleted, userState);
        }
        
        private void OnGetHQPoRequisitionOperationCompleted(object arg) {
            if ((this.GetHQPoRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHQPoRequisitionCompleted(this, new GetHQPoRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eshopinf.org/GetJJTPoRequisition", RequestNamespace="http://eshopinf.org/", ResponseNamespace="http://eshopinf.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetJJTPoRequisition(System.DateTime dayFrom, System.DateTime dayTo) {
            object[] results = this.Invoke("GetJJTPoRequisition", new object[] {
                        dayFrom,
                        dayTo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetJJTPoRequisitionAsync(System.DateTime dayFrom, System.DateTime dayTo) {
            this.GetJJTPoRequisitionAsync(dayFrom, dayTo, null);
        }
        
        /// <remarks/>
        public void GetJJTPoRequisitionAsync(System.DateTime dayFrom, System.DateTime dayTo, object userState) {
            if ((this.GetJJTPoRequisitionOperationCompleted == null)) {
                this.GetJJTPoRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetJJTPoRequisitionOperationCompleted);
            }
            this.InvokeAsync("GetJJTPoRequisition", new object[] {
                        dayFrom,
                        dayTo}, this.GetJJTPoRequisitionOperationCompleted, userState);
        }
        
        private void OnGetJJTPoRequisitionOperationCompleted(object arg) {
            if ((this.GetJJTPoRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetJJTPoRequisitionCompleted(this, new GetJJTPoRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eshopinf.org/AddPoRequisition", RequestNamespace="http://eshopinf.org/", ResponseNamespace="http://eshopinf.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddPoRequisition(int headerId, int lineId, decimal quantity, string logInfo) {
            object[] results = this.Invoke("AddPoRequisition", new object[] {
                        headerId,
                        lineId,
                        quantity,
                        logInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AddPoRequisitionAsync(int headerId, int lineId, decimal quantity, string logInfo) {
            this.AddPoRequisitionAsync(headerId, lineId, quantity, logInfo, null);
        }
        
        /// <remarks/>
        public void AddPoRequisitionAsync(int headerId, int lineId, decimal quantity, string logInfo, object userState) {
            if ((this.AddPoRequisitionOperationCompleted == null)) {
                this.AddPoRequisitionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPoRequisitionOperationCompleted);
            }
            this.InvokeAsync("AddPoRequisition", new object[] {
                        headerId,
                        lineId,
                        quantity,
                        logInfo}, this.AddPoRequisitionOperationCompleted, userState);
        }
        
        private void OnAddPoRequisitionOperationCompleted(object arg) {
            if ((this.AddPoRequisitionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPoRequisitionCompleted(this, new AddPoRequisitionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eshopinf.org/GetPoKinetic", RequestNamespace="http://eshopinf.org/", ResponseNamespace="http://eshopinf.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPoKinetic() {
            object[] results = this.Invoke("GetPoKinetic", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPoKineticAsync() {
            this.GetPoKineticAsync(null);
        }
        
        /// <remarks/>
        public void GetPoKineticAsync(object userState) {
            if ((this.GetPoKineticOperationCompleted == null)) {
                this.GetPoKineticOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPoKineticOperationCompleted);
            }
            this.InvokeAsync("GetPoKinetic", new object[0], this.GetPoKineticOperationCompleted, userState);
        }
        
        private void OnGetPoKineticOperationCompleted(object arg) {
            if ((this.GetPoKineticCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPoKineticCompleted(this, new GetPoKineticCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eshopinf.org/UpdatePoKinetic", RequestNamespace="http://eshopinf.org/", ResponseNamespace="http://eshopinf.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdatePoKinetic(string lineId, string comments) {
            object[] results = this.Invoke("UpdatePoKinetic", new object[] {
                        lineId,
                        comments});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePoKineticAsync(string lineId, string comments) {
            this.UpdatePoKineticAsync(lineId, comments, null);
        }
        
        /// <remarks/>
        public void UpdatePoKineticAsync(string lineId, string comments, object userState) {
            if ((this.UpdatePoKineticOperationCompleted == null)) {
                this.UpdatePoKineticOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePoKineticOperationCompleted);
            }
            this.InvokeAsync("UpdatePoKinetic", new object[] {
                        lineId,
                        comments}, this.UpdatePoKineticOperationCompleted, userState);
        }
        
        private void OnUpdatePoKineticOperationCompleted(object arg) {
            if ((this.UpdatePoKineticCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePoKineticCompleted(this, new UpdatePoKineticCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetPoRequisitionCompletedEventHandler(object sender, GetPoRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPoRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPoRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetHQPoRequisitionCompletedEventHandler(object sender, GetHQPoRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHQPoRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHQPoRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetJJTPoRequisitionCompletedEventHandler(object sender, GetJJTPoRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetJJTPoRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetJJTPoRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void AddPoRequisitionCompletedEventHandler(object sender, AddPoRequisitionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddPoRequisitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddPoRequisitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void GetPoKineticCompletedEventHandler(object sender, GetPoKineticCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPoKineticCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPoKineticCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void UpdatePoKineticCompletedEventHandler(object sender, UpdatePoKineticCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePoKineticCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePoKineticCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591